name: Deploy to GitHub pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build static files
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: yarn install
    - run: yarn build
    
    - name: Deploy to Azure
      uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
      with:
        source-path: public
        sas-url: ${{ secrets.STORAGE_SAS_TOKEN }}
        
